require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "api/v1/by_lines", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ByLine. As you add validations to ByLine, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { name: 'Writer' } }

  let(:invalid_attributes) { { name: '' }  }


  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ByLinesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    { "ACCEPT" => "application/json" }
  }

  describe "GET /index" do
    it "renders a successful response" do
      ByLine.create! valid_attributes
      get api_v1_by_lines_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      by_line = ByLine.create! valid_attributes
      get api_v1_by_line_url(by_line), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ByLine" do
        expect {
          post api_v1_by_lines_url,
               params: { by_line: valid_attributes }, headers: valid_headers, as: :json
        }.to change(ByLine, :count).by(1)
      end

      it "renders a JSON response with the new by_line" do
        post api_v1_by_lines_url,
             params: { by_line: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ByLine" do
        expect {
          post api_v1_by_lines_url,
               params: { by_line: invalid_attributes }, as: :json
        }.to change(ByLine, :count).by(0)
      end

      it "renders a JSON response with errors for the new by_line" do
        post by_lines_url,
             params: { by_line: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Artist" }
      }

      it "updates the requested by_line" do
        by_line = ByLine.create! valid_attributes
        patch by_line_url(by_line),
              params: { by_line: new_attributes }, headers: valid_headers, as: :json
        by_line.reload
        expect(by_line.name).to eq("Artist")
      end

      it "renders a JSON response with the by_line" do
        by_line = ByLine.create! valid_attributes
        patch by_line_url(by_line),
              params: { by_line: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the by_line" do
        by_line = ByLine.create! valid_attributes
        patch api_v1_by_line_url(by_line),
              params: { by_line: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested by_line" do
      by_line = ByLine.create! valid_attributes
      expect {
        delete by_line_url(by_line), headers: valid_headers, as: :json
      }.to change(ByLine, :count).by(-1)
    end
  end
end
