require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/collections", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Collection. As you add validations to Collection, be sure to
  # adjust the attributes here as well.
  let(:user) { User.create!(name: "John Doe", email: "john@example.com") }

  let(:valid_attributes) {
    { user_id: user.id }
  }

  let(:invalid_attributes) {
    { user_id: nil }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CollectionsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Collection.create! valid_attributes
      get api_v1_collections_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      collection = Collection.create! valid_attributes
      get api_v1_collection_url(collection), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Collection" do
        expect {
          post api_v1_collections_url,
               params: { collection: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Collection, :count).by(1)
      end

      it "renders a JSON response with the new collection" do
        post api_v1_collections_url,
             params: { collection: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Collection" do
        expect {
          post api_v1_collections_url,
               params: { collection: invalid_attributes }, as: :json
        }.to change(Collection, :count).by(0)
      end

      it "renders a JSON response with errors for the new collection" do
        post api_v1_collections_url,
             params: { collection: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_user) { User.create!(name: "Jane Doe", email: "jane@example.com") }
      let(:new_attributes) {
        { user_id: new_user.id }
      }

      it "updates the requested collection" do
        collection = Collection.create! valid_attributes
        patch api_v1_collection_url(collection),
              params: { collection: new_attributes }, headers: valid_headers, as: :json
        collection.reload
        expect(collection.user_id).to eq(new_user.id)
      end

      it "renders a JSON response with the collection" do
        collection = Collection.create! valid_attributes
        patch api_v1_collection_url(collection),
              params: { collection: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the collection" do
        collection = Collection.create! valid_attributes
        patch api_v1_collection_url(collection),
              params: { collection: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested collection" do
      collection = Collection.create! valid_attributes
      expect {
        delete api_v1_collection_url(collection), headers: valid_headers, as: :json
      }.to change(Collection, :count).by(-1)
    end
  end
end
