require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/conditions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Condition. As you add validations to Condition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Near Mint" }
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  let(:condition) { create(:condition, name: 'Near Mint') }
  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ConditionsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    let!(:condition) { create(:condition, name: 'Near Mint') }
    it "renders a successful response" do
      get api_v1_conditions_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    let!(:condition) { create(:condition, name: 'Near Mint') }
    it "renders a successful response" do
      get api_v1_condition_url(condition), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Condition" do
        expect {
          post api_v1_conditions_url,
               params: { condition: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Condition, :count).by(1)
      end

      it "renders a JSON response with the new condition" do
        post api_v1_conditions_url,
             params: { condition: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Condition" do
        expect {
          post api_v1_conditions_url,
               params: { condition: invalid_attributes }, as: :json
        }.to change(Condition, :count).by(0)
      end

      it "renders a JSON response with errors for the new condition" do
        post api_v1_conditions_url,
             params: { condition: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Very Fine" }
      }
      let!(:condition) { create(:condition, name: 'Near Mint') }

      it "updates the requested condition" do
        patch api_v1_condition_url(condition),
              params: { condition: new_attributes }, headers: valid_headers, as: :json
        condition.reload
        expect(condition.name).to eq("Very Fine")
      end

      it "renders a JSON response with the condition" do
        patch api_v1_condition_url(condition),
              params: { condition: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      let!(:condition) { create(:condition, name: 'Near Mint') }
      it "renders a JSON response with errors for the condition" do
        patch api_v1_condition_url(condition),
              params: { condition: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    let!(:condition) { create(:condition, name: 'Near Mint') }
    it "destroys the requested condition" do
      expect {
        delete api_v1_condition_url(condition), headers: valid_headers, as: :json
      }.to change(Condition, :count).by(-1)
    end
  end
end
