require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/covers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Cover. As you add validations to Cover, be sure to
  # adjust the attributes here as well.
  let(:publication_type) { create!(:publication_type, name: "Comic Book") }
  let(:publisher) { create!(:publisher, name: "Marvel Comics") }
  let(:publication) { create!(:publication, title: "Amazing Spider-Man", publication_type_id: publication_type.id, publisher_id: publisher.id) }
  let(:issue) { Issue.create!(:issue, number: 1, publication_id: publication.id) }

  let(:valid_attributes) {
    { variant: "Regular", issue_id: issue.id }
  }

  let(:invalid_attributes) {
    { variant: "Regular", issue_id: nil }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CoversController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cover.create! valid_attributes
      get covers_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cover = Cover.create! valid_attributes
      get cover_url(cover), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cover" do
        expect {
          post covers_url,
               params: { cover: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Cover, :count).by(1)
      end

      it "renders a JSON response with the new cover" do
        post covers_url,
             params: { cover: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cover" do
        expect {
          post covers_url,
               params: { cover: invalid_attributes }, as: :json
        }.to change(Cover, :count).by(0)
      end

      it "renders a JSON response with errors for the new cover" do
        post covers_url,
             params: { cover: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { variant: "Variant Cover" }
      }

      it "updates the requested cover" do
        cover = Cover.create! valid_attributes
        patch cover_url(cover),
              params: { cover: new_attributes }, headers: valid_headers, as: :json
        cover.reload
        expect(cover.variant).to eq("Variant Cover")
      end

      it "renders a JSON response with the cover" do
        cover = Cover.create! valid_attributes
        patch cover_url(cover),
              params: { cover: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the cover" do
        cover = Cover.create! valid_attributes
        patch cover_url(cover),
              params: { cover: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cover" do
      cover = Cover.create! valid_attributes
      expect {
        delete cover_url(cover), headers: valid_headers, as: :json
      }.to change(Cover, :count).by(-1)
    end
  end
end
