require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/publishers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Publisher. As you add validations to Publisher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Marvel Comics" }
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # PublishersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Publisher.create! valid_attributes
      get publishers_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      publisher = Publisher.create! valid_attributes
      get publisher_url(publisher), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Publisher" do
        expect {
          post publishers_url,
               params: { publisher: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Publisher, :count).by(1)
      end

      it "renders a JSON response with the new publisher" do
        post publishers_url,
             params: { publisher: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Publisher" do
        expect {
          post publishers_url,
               params: { publisher: invalid_attributes }, as: :json
        }.to change(Publisher, :count).by(0)
      end

      it "renders a JSON response with errors for the new publisher" do
        post publishers_url,
             params: { publisher: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "DC Comics" }
      }

      it "updates the requested publisher" do
        publisher = Publisher.create! valid_attributes
        patch publisher_url(publisher),
              params: { publisher: new_attributes }, headers: valid_headers, as: :json
        publisher.reload
        expect(publisher.name).to eq("DC Comics")
      end

      it "renders a JSON response with the publisher" do
        publisher = Publisher.create! valid_attributes
        patch publisher_url(publisher),
              params: { publisher: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the publisher" do
        publisher = Publisher.create! valid_attributes
        patch publisher_url(publisher),
              params: { publisher: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested publisher" do
      publisher = Publisher.create! valid_attributes
      expect {
        delete publisher_url(publisher), headers: valid_headers, as: :json
      }.to change(Publisher, :count).by(-1)
    end
  end
end
