name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    # PostgreSQL Service Container
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: cbdb_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # Setup Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2" # Match your project's Ruby version
          bundler-cache: true

      # Configure Database
      - name: Configure PostgreSQL
        env:
          POSTGRES_DB: cbdb_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        run: |
          sudo apt-get install -y postgresql-client
          psql -c 'create database cbdb_test;' -U testuser -h localhost

      # Install Dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          yarn install

      # Database Preparation
      - name: Prepare database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/cbdb_test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed

      # Run Tests
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/cbdb_test
        run: |
          bundle exec rspec
