name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    # PostgreSQL Service Container
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: cbdb_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # Setup Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2" # Match your project's Ruby version
          bundler-cache: true

      # Configure Database Connection
      - name: Configure database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cbdb_test
        run: |
          # Verify PostgreSQL is running
          pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER

      - name: Verify PostgreSQL Connection
        run: |
          # Explicitly check TCP connection
          psql -h localhost -p 5432 -U postgres -d postgres -c "SELECT 1" || exit 1

      # Update Database Configuration
      - name: Prepare database configuration
        run: |
          # Explicitly set host to localhost and use TCP connection
          sed -i 's/host: .*/host: localhost/g' config/database.yml
          sed -i 's/adapter: postgresql/adapter: postgresql\n  host: localhost/g' config/database.yml
          
          # Ensure test database configuration is correct
          cat > config/database.yml << EOF
          test:
            adapter: postgresql
            encoding: unicode
            database: cbdb_test
            username: postgres
            password: postgres
            host: localhost
            port: 5432
            pool: 5
          EOF

        cat config/database.yml

      # Install Dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Prepare Database
      - name: Prepare database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_DB: cbdb_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails db:migrate

      # Run Tests
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_DB: cbdb_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rspec
