name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    # PostgreSQL Service Container
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: cbdb_test
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        # Health check to ensure database is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      # Setup Language/Runtime
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Dependency Management
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov psycopg2-binary

      # Database Migration Preparation
      - name: Install Database Migration Tools
        run: |
          pip install alembic
          # If using a different migration tool, adjust accordingly

      # Database Migration
      - name: Run Database Migrations
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/cbdb_test
        run: |
          # Assuming Alembic is used for migrations
          alembic upgrade head

          # Alternative if using custom migration script
          # python db_migrate.py

      # Run Tests with Coverage
      - name: Run Tests
        env:
          # Database connection parameters
          TEST_DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/cbdb_test
          # Add other necessary environment variables
        run: |
          pytest tests/ \
            --cov=. \
            --cov-report=xml \
            --cov-report=term-missingtest:prepare test
